### ISSUE TITLE
IllegalStateException in com.slidingmenu.lib.CustomViewAbove.onLayout(CustomViewAbove.java:551)

### ISSUE THREAD

**Issue by bartwell** [jfeinstein10/SlidingMenu#132]
I have the layout with this code:

```
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout android:layout_width="fill_parent"
    android:layout_height="fill_parent"
    android:clickable="true"
    android:focusable="true"
    android:gravity="center"
    android:orientation="vertical" xmlns:android="http://schemas.android.com/apk/res/android">

    <FrameLayout
        android:id="@+id/header"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
         >
    </FrameLayout>

    <ListView
        android:id="@+id/listView1"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_weight="1" >
    </ListView>

</LinearLayout>
```

It worked done, but sometimes I get IllegalStateException at com.slidingmenu.lib.CustomViewAbove.onLayout(CustomViewAbove.java:551):

```
mContent.layout(contentLeft, 0, contentLeft + width, height);
```

Is it possible to fix it? It works fine when I move FrameLayout under ListView.

Full exception text:

```
11-07 14:25:54.435: E/AndroidRuntime(23025): java.lang.IllegalStateException: The content of the adapter has changed but ListView did not receive a notification. Make sure the content of your adapter is not modified from a background thread, but only from the UI thread. [in ListView(2130968597, class android.widget.ListView) with Adapter(class ru.bartwell.mypkg.MyArrayAdapter)]
11-07 14:25:54.435: E/AndroidRuntime(23025):    at android.widget.ListView.layoutChildren(ListView.java:1538)
11-07 14:25:54.435: E/AndroidRuntime(23025):    at android.widget.AbsListView.onLayout(AbsListView.java:2044)
11-07 14:25:54.435: E/AndroidRuntime(23025):    at android.view.View.layout(View.java:11418)
11-07 14:25:54.435: E/AndroidRuntime(23025):    at android.view.ViewGroup.layout(ViewGroup.java:4224)
11-07 14:25:54.435: E/AndroidRuntime(23025):    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1628)
11-07 14:25:54.435: E/AndroidRuntime(23025):    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1486)
11-07 14:25:54.435: E/AndroidRuntime(23025):    at android.widget.LinearLayout.onLayout(LinearLayout.java:1399)
11-07 14:25:54.435: E/AndroidRuntime(23025):    at android.view.View.layout(View.java:11418)
11-07 14:25:54.435: E/AndroidRuntime(23025):    at android.view.ViewGroup.layout(ViewGroup.java:4224)
11-07 14:25:54.435: E/AndroidRuntime(23025):    at android.widget.FrameLayout.onLayout(FrameLayout.java:431)
11-07 14:25:54.435: E/AndroidRuntime(23025):    at android.view.View.layout(View.java:11418)
11-07 14:25:54.435: E/AndroidRuntime(23025):    at android.view.ViewGroup.layout(ViewGroup.java:4224)
11-07 14:25:54.435: E/AndroidRuntime(23025):    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1628)
11-07 14:25:54.435: E/AndroidRuntime(23025):    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1486)
11-07 14:25:54.435: E/AndroidRuntime(23025):    at android.widget.LinearLayout.onLayout(LinearLayout.java:1399)
11-07 14:25:54.435: E/AndroidRuntime(23025):    at android.view.View.layout(View.java:11418)
11-07 14:25:54.435: E/AndroidRuntime(23025):    at android.view.ViewGroup.layout(ViewGroup.java:4224)
11-07 14:25:54.435: E/AndroidRuntime(23025):    at android.widget.FrameLayout.onLayout(FrameLayout.java:431)
11-07 14:25:54.435: E/AndroidRuntime(23025):    at android.view.View.layout(View.java:11418)
11-07 14:25:54.435: E/AndroidRuntime(23025):    at android.view.ViewGroup.layout(ViewGroup.java:4224)
11-07 14:25:54.435: E/AndroidRuntime(23025):    at com.slidingmenu.lib.CustomViewAbove.onLayout(CustomViewAbove.java:551)
11-07 14:25:54.435: E/AndroidRuntime(23025):    at android.view.View.layout(View.java:11418)
11-07 14:25:54.435: E/AndroidRuntime(23025):    at android.view.ViewGroup.layout(ViewGroup.java:4224)
11-07 14:25:54.435: E/AndroidRuntime(23025):    at android.widget.RelativeLayout.onLayout(RelativeLayout.java:925)
11-07 14:25:54.435: E/AndroidRuntime(23025):    at android.view.View.layout(View.java:11418)
11-07 14:25:54.435: E/AndroidRuntime(23025):    at android.view.ViewGroup.layout(ViewGroup.java:4224)
11-07 14:25:54.435: E/AndroidRuntime(23025):    at android.widget.FrameLayout.onLayout(FrameLayout.java:431)
11-07 14:25:54.435: E/AndroidRuntime(23025):    at android.view.View.layout(View.java:11418)
11-07 14:25:54.435: E/AndroidRuntime(23025):    at android.view.ViewGroup.layout(ViewGroup.java:4224)
11-07 14:25:54.435: E/AndroidRuntime(23025):    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1628)
11-07 14:25:54.435: E/AndroidRuntime(23025):    at android.view.ViewRootImpl.handleMessage(ViewRootImpl.java:2585)
11-07 14:25:54.435: E/AndroidRuntime(23025):    at android.os.Handler.dispatchMessage(Handler.java:99)
11-07 14:25:54.435: E/AndroidRuntime(23025):    at android.os.Looper.loop(Looper.java:137)
11-07 14:25:54.435: E/AndroidRuntime(23025):    at android.app.ActivityThread.main(ActivityThread.java:4507)
11-07 14:25:54.435: E/AndroidRuntime(23025):    at java.lang.reflect.Method.invokeNative(Native Method)
11-07 14:25:54.435: E/AndroidRuntime(23025):    at java.lang.reflect.Method.invoke(Method.java:511)
11-07 14:25:54.435: E/AndroidRuntime(23025):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:790)
11-07 14:25:54.435: E/AndroidRuntime(23025):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:557)
11-07 14:25:54.435: E/AndroidRuntime(23025):    at dalvik.system.NativeStart.main(Native Method)
```

**Comment by evixar** [comment]
Hi,

I've got the same problem. Did you manage to fix it ? It seems to happen not all the time ... can't figure out why

Regards

**Comment by hoangpn412** [comment]
Hi, I've got the same problem. Somebody may fix it?

**Comment by mjkohoh** [comment]
But the Exception text said that this exception is caused by modifying adapter in background thread,not in UIthread.
So I don't think it's SlidingMenu library‘s problem

**Comment by DjekGolub** [comment]
I think the problem is not a library. But the library hides the true stack traces errors and it's bad. It is happen often with different  crashes.

My problem: list (which does not belong to the library) changed in not UI thread - it created to fail, but the library intercepted stack trace and I got this error (IllegalStateException in com.slidingmenu.lib.CustomViewAbove.onLayout(CustomViewAbove.java:551)).

**Comment by bartwell** [comment]
The problem is happened when notifyDataSetChanged() calling often (thank's to Carnal: http://stackoverflow.com/questions/19077626/illegalstateexception-in-pulltorefreshlistviewinternallistviewsdk9#comment28298861_19077626). I add queue in my application and add content by timer. By this way I solved this problem.
