### ISSUE TITLE
pointerIndex out of range Exception when first touch is on Android navigation bar

### ISSUE THREAD

**Issue by pfihl** [jfeinstein10/SlidingMenu#224]
Hi

The pointerIndex out of range Exception was reported earlier (https://github.com/jfeinstein10/SlidingMenu/issues/94) and the issue is closed but the exception still occurs.

If I first touch the Android navigation bar and then try to slide the menu with another finger, then I get the exception.

![NavigationBar](http://developer.android.com/design/media/whats_new_nav_bar.png)

The issue usually happens because the the palm of the hand touches the bottom corner of the screen when extending the thumb across the screen.

LogCat output (using Master branch from Jan. 10th 2013)

```
01-11 13:35:18.397: E/AndroidRuntime(17540): FATAL EXCEPTION: main
01-11 13:35:18.397: E/AndroidRuntime(17540): java.lang.IllegalArgumentException: pointerIndex out of range
01-11 13:35:18.397: E/AndroidRuntime(17540):    at android.view.MotionEvent.nativeGetAxisValue(Native Method)
01-11 13:35:18.397: E/AndroidRuntime(17540):    at android.view.MotionEvent.getX(MotionEvent.java:1981)
01-11 13:35:18.397: E/AndroidRuntime(17540):    at android.support.v4.view.MotionEventCompatEclair.getX(MotionEventCompatEclair.java:32)
01-11 13:35:18.397: E/AndroidRuntime(17540):    at android.support.v4.view.MotionEventCompat$EclairMotionEventVersionImpl.getX(MotionEventCompat.java:91)
01-11 13:35:18.397: E/AndroidRuntime(17540):    at android.support.v4.view.MotionEventCompat.getX(MotionEventCompat.java:219)
01-11 13:35:18.397: E/AndroidRuntime(17540):    at com.slidingmenu.lib.CustomViewAbove.onInterceptTouchEvent(CustomViewAbove.java:640)
01-11 13:35:18.397: E/AndroidRuntime(17540):    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1817)
01-11 13:35:18.397: E/AndroidRuntime(17540):    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2174)
01-11 13:35:18.397: E/AndroidRuntime(17540):    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
01-11 13:35:18.397: E/AndroidRuntime(17540):    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2174)
01-11 13:35:18.397: E/AndroidRuntime(17540):    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
01-11 13:35:18.397: E/AndroidRuntime(17540):    at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:1953)
01-11 13:35:18.397: E/AndroidRuntime(17540):    at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1405)
01-11 13:35:18.397: E/AndroidRuntime(17540):    at android.app.Activity.dispatchTouchEvent(Activity.java:2410)
01-11 13:35:18.397: E/AndroidRuntime(17540):    at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:1901)
01-11 13:35:18.397: E/AndroidRuntime(17540):    at android.view.View.dispatchPointerEvent(View.java:7419)
01-11 13:35:18.397: E/AndroidRuntime(17540):    at android.view.ViewRootImpl.deliverPointerEvent(ViewRootImpl.java:3220)
01-11 13:35:18.397: E/AndroidRuntime(17540):    at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:3165)
01-11 13:35:18.397: E/AndroidRuntime(17540):    at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:4292)
01-11 13:35:18.397: E/AndroidRuntime(17540):    at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:4271)
01-11 13:35:18.397: E/AndroidRuntime(17540):    at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:4363)
01-11 13:35:18.397: E/AndroidRuntime(17540):    at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:179)
01-11 13:35:18.397: E/AndroidRuntime(17540):    at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
01-11 13:35:18.397: E/AndroidRuntime(17540):    at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:171)
01-11 13:35:18.397: E/AndroidRuntime(17540):    at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:4342)
01-11 13:35:18.397: E/AndroidRuntime(17540):    at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:4382)
01-11 13:35:18.397: E/AndroidRuntime(17540):    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:749)
01-11 13:35:18.397: E/AndroidRuntime(17540):    at android.view.Choreographer.doCallbacks(Choreographer.java:562)
01-11 13:35:18.397: E/AndroidRuntime(17540):    at android.view.Choreographer.doFrame(Choreographer.java:530)
01-11 13:35:18.397: E/AndroidRuntime(17540):    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:735)
01-11 13:35:18.397: E/AndroidRuntime(17540):    at android.os.Handler.handleCallback(Handler.java:725)
01-11 13:35:18.397: E/AndroidRuntime(17540):    at android.os.Handler.dispatchMessage(Handler.java:92)
01-11 13:35:18.397: E/AndroidRuntime(17540):    at android.os.Looper.loop(Looper.java:137)
01-11 13:35:18.397: E/AndroidRuntime(17540):    at android.app.ActivityThread.main(ActivityThread.java:5039)
01-11 13:35:18.397: E/AndroidRuntime(17540):    at java.lang.reflect.Method.invokeNative(Native Method)
01-11 13:35:18.397: E/AndroidRuntime(17540):    at java.lang.reflect.Method.invoke(Method.java:511)
01-11 13:35:18.397: E/AndroidRuntime(17540):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
01-11 13:35:18.397: E/AndroidRuntime(17540):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
01-11 13:35:18.397: E/AndroidRuntime(17540):    at dalvik.system.NativeStart.main(Native Method)
```

**Comment by pfihl** [comment]
Thanks. The posted fix works for me.
