### ISSUE TITLE
IllegalStateException

### ISSUE THREAD

**Issue by pathpainter** [jfeinstein10/SlidingMenu#227]
Hi,

First of all, thank you for this great library. Brilliant job!
I have included it in my app. Most of the times it works without problems, but sometimes I get an IllegalStateException saying that my class SideMenuItemListFragment (which extends ListFragment) did not create a view.

My class BaseFragmentActivity extends SlidingFragmentActivity (which extends SherlockFragmentActivity) and implements SideMenuItemListFragment.Callbacks.

In BaseFragmentActivity.java, line 79 I have: 
    public void customizeBehindView()
    {
        setBehindContentView(R.layout.sidemenu_item_list);

```
    if (getSupportFragmentManager().findFragmentByTag(TAG) == null) {
        FragmentTransaction t = getSupportFragmentManager().beginTransaction();
        t.add(R.id.item_list, new SideMenuItemListFragment());
        t.commit();
    }
}
```

And below is part of the trace. Is this an issue related to the library or something that I am doing wrong.

Thank you very much.
David

Caused by: java.lang.IllegalStateException: Fragment com.example.mypackage.fragments.SideMenuItemListFragment did not create a view.
    at android.support.v4.app.FragmentActivity.onCreateView(FragmentActivity.java:293)
    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:563)
    ... 22 more
java.lang.IllegalStateException: Fragment com.example.mypackage.fragments.SideMenuItemListFragment did not create a view.
    at android.support.v4.app.FragmentActivity.onCreateView(FragmentActivity.java:293)
    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:563)
    at android.view.LayoutInflater.rInflate(LayoutInflater.java:623)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:408)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:320)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:276)
    at com.slidingmenu.lib.app.SlidingFragmentActivity.setBehindContentView(SlidingFragmentActivity.java:84)
    at com.example.mypackage.activities.BaseFragmentActivity.customizeBehindView(BaseFragmentActivity.java:79)
    at com.example.mypackage.activities.BaseFragmentActivity.onCreate(BaseFragmentActivity.java:63)
    at com.example.mypackage.activities.RoutesActivity.onCreate(RoutesActivity.java:33)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1047)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1615)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1667)
    at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:2836)
    at android.app.ActivityThread.access$1600(ActivityThread.java:117)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:939)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:130)
    at android.app.ActivityThread.main(ActivityThread.java:3687)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:507)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:842)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)

**Comment by jfeinstein10** [comment]
I'm sorry but this is an issue with your Fragment, not the library.
