### ISSUE TITLE
java.lang.IllegalArgumentException: pointerIndex out of range

### ISSUE THREAD

**Issue by ovy9086** [jfeinstein10/SlidingMenu#323]
Hello,

I am using slidingmenu 1.0 .

I receive the following crash from the SlidingMenuLib :

java.lang.IllegalArgumentException: pointerIndex out of range
    at android.view.MotionEvent.nativeGetAxisValue(Native Method)
    at android.view.MotionEvent.getX(MotionEvent.java:1974)
    at android.support.v4.view.MotionEventCompatEclair.getX(MotionEventCompatEclair.java:32)
    at android.support.v4.view.MotionEventCompat$EclairMotionEventVersionImpl.getX(MotionEventCompat.java:91)
    at android.support.v4.view.MotionEventCompat.getX(MotionEventCompat.java:219)
    at com.slidingmenu.lib.CustomViewAbove.onInterceptTouchEvent(CustomViewAbove.java:637)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1629)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:1957)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1726)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:1957)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1726)
    at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:1937)
    at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1372)
    at android.app.Activity.dispatchTouchEvent(Activity.java:2418)
    at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:1885)
    at android.view.View.dispatchPointerEvent(View.java:5731)
    at android.view.ViewRootImpl.deliverPointerEvent(ViewRootImpl.java:2900)
    at android.view.ViewRootImpl.handleMessage(ViewRootImpl.java:2476)
    at android.view.ViewRootImpl.processInputEvents(ViewRootImpl.java:849)
    at android.view.ViewRootImpl.handleMessage(ViewRootImpl.java:2485)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:137)
    at android.app.ActivityThread.main(ActivityThread.java:4464)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:511)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:822)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:589)
    at dalvik.system.NativeStart.main(Native Method)

Device :
Android: 4.0.3
Manufacturer: LGE
Model: LG-P700

**Comment by jfeinstein10** [comment]
Duplicate.
