### ISSUE TITLE
Sliding menu on a SherlockListActivity 

### ISSUE THREAD

**Issue by beatnyama** [jfeinstein10/SlidingMenu#388]
Attempting to use the sliding menu on a SherlockListActivity (which has no setContentView) together with this code

```
menu = new SlidingMenu(this);
menu.setMode(SlidingMenu.LEFT);
.......
........
```

   menu.attachToActivity(this, SlidingMenu.SLIDING_CONTENT);

results in this error

Caused by: java.lang.NullPointerException
at android.view.ViewGroup.addView(ViewGroup.java:3427)
at android.view.ViewGroup.addView(ViewGroup.java:3410)
at com.slidingmenu.lib.CustomViewAbove.setContent(CustomViewAbove.java:436)
at com.slidingmenu.lib.SlidingMenu.setContent(SlidingMenu.java:351)

Is this the correct way of using the slidingmenu on a listactivity which does not have setContentView?

**Comment by beatnyama** [comment]
I found solution that works:

Make your  activity extends SherlockFragmentActivity (or FragmentActivity if not using Sherlock)
Declare a private variable for my listview

Setcontentview and set it to a layout with a listview as its only element

include the code to setup the menu as indicated 

```
    // configure the SlidingMenu
    menu = new SlidingMenu(this);
    menu.setMode(SlidingMenu.LEFT);
            ......................
```

To set the adaptor use 

```
            listview.setAdapter(adaptor);
```

To identify clicked items on the listview use onItemClickListener

```
            listview.setOnItemClickListener(new OnItemClickListener(){
```

This then means you get to have your listview working properly and your sliding menu working as well
