### ISSUE TITLE
SlidingMenu java.lang.IllegalArgumentExcpetion

### ISSUE THREAD

**Issue by dr03lf** [jfeinstein10/SlidingMenu#421]
Occured as I swiped through my app like a crazy monkey. No clues how this happend or how to reproduce it.

05-15 13:41:43.483: ERROR/InputEventReceiver(14986): Exception dispatching input event.
05-15 13:41:43.483: ERROR/MessageQueue-JNI(14986): Exception in MessageQueue callback: handleReceiveCallback
05-15 13:41:43.503: ERROR/MessageQueue-JNI(14986): java.lang.IllegalArgumentException: pointerIndex out of range
        at android.view.MotionEvent.nativeGetAxisValue(Native Method)
        at android.view.MotionEvent.getX(MotionEvent.java:1981)
        at android.support.v4.view.MotionEventCompatEclair.getX(MotionEventCompatEclair.java:32)
        at android.support.v4.view.MotionEventCompat$EclairMotionEventVersionImpl.getX(MotionEventCompat.java:91)
        at android.support.v4.view.MotionEventCompat.getX(MotionEventCompat.java:219)
        at com.slidingmenu.lib.CustomViewAbove.determineDrag(CustomViewAbove.java:785)
        at com.slidingmenu.lib.CustomViewAbove.onTouchEvent(CustomViewAbove.java:701)
        at android.view.View.dispatchTouchEvent(View.java:7246)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2168)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1903)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2174)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2174)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
        at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:1953)
        at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1405)
        at android.app.Activity.dispatchTouchEvent(Activity.java:2410)
        at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:1901)
        at android.view.View.dispatchPointerEvent(View.java:7426)
        at android.view.ViewRootImpl.deliverPointerEvent(ViewRootImpl.java:3220)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:3165)
        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:4292)
        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:4271)
        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:4363)
        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:179)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:125)
        at android.os.Looper.loop(Looper.java:124)
        at android.app.ActivityThread.main(ActivityThread.java:5041)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:511)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
        at dalvik.system.NativeStart.main(Native Method)
05-15 13:41:43.503: WARN/dalvikvm(14986): threadid=1: thread exiting with uncaught exception (group=0x40b95930)
05-15 13:41:43.503: ERROR/AndroidRuntime(14986): FATAL EXCEPTION: main
        java.lang.IllegalArgumentException: pointerIndex out of range
        at android.view.MotionEvent.nativeGetAxisValue(Native Method)
        at android.view.MotionEvent.getX(MotionEvent.java:1981)
        at android.support.v4.view.MotionEventCompatEclair.getX(MotionEventCompatEclair.java:32)
        at android.support.v4.view.MotionEventCompat$EclairMotionEventVersionImpl.getX(MotionEventCompat.java:91)
        at android.support.v4.view.MotionEventCompat.getX(MotionEventCompat.java:219)
        at com.slidingmenu.lib.CustomViewAbove.determineDrag(CustomViewAbove.java:785)
        at com.slidingmenu.lib.CustomViewAbove.onTouchEvent(CustomViewAbove.java:701)
        at android.view.View.dispatchTouchEvent(View.java:7246)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2168)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1903)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2174)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2174)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
        at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:1953)
        at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1405)
        at android.app.Activity.dispatchTouchEvent(Activity.java:2410)
        at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:1901)
        at android.view.View.dispatchPointerEvent(View.java:7426)
        at android.view.ViewRootImpl.deliverPointerEvent(ViewRootImpl.java:3220)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:3165)
        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:4292)
        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:4271)
        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:4363)
        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:179)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:125)
        at android.os.Looper.loop(Looper.java:124)
        at android.app.ActivityThread.main(ActivityThread.java:5041)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:511)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
        at dalvik.system.NativeStart.main(Native Method)

**Comment by jfeinstein10** [comment]
This is not an issue. If you have questions, then please ask them on StackOverflow or elsewhere. Thanks!
