### ISSUE TITLE
SlidingMapActivity with SupportMapFragment

### ISSUE THREAD

**Issue by bastienbeurier** [jfeinstein10/SlidingMenu#428]
Does SlidingMapActivity works with a SupportMapFragment instead of the new MapFragment? I am getting a exception when trying to inflate de map fragment: 

 java.lang.RuntimeException: Unable to start activity ComponentInfo{com.streetshout.android/com.streetshout.android.Activities.MainActivity}: android.view.InflateException: Binary XML file line #7: Error inflating class fragment
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2180)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2230)
        at android.app.ActivityThread.access$600(ActivityThread.java:141)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:137)
        at android.app.ActivityThread.main(ActivityThread.java:5041)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:511)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
        at dalvik.system.NativeStart.main(Native Method)
        Caused by: android.view.InflateException: Binary XML file line #7: Error inflating class fragment
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:746)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:352)
        at com.jeremyfeinstein.slidingmenu.lib.app.SlidingMapActivity.setContentView(SlidingMapActivity.java:59)
        at com.streetshout.android.Activities.MainActivity.onCreate(MainActivity.java:87)

 I am trying to make my app compatible with older android version. 

Thanks!

**Comment by bastienbeurier** [comment]
Oups sorry, apparently it is not related to the SlidingMenu library!
