### ISSUE TITLE
java.lang.noclassdeffounderror: com.jeremyfeinstein.slidingmenu.lib.R$styleable

### ISSUE THREAD

**Issue by waqasw** [jfeinstein10/SlidingMenu#437]
I followed what you have explained in the setup i.e. cleaning the project and making it as dependency project and I don't have any error but when I run it the app crashes and I get below error
java.lang.noclassdeffounderror: com.jeremyfeinstein.slidingmenu.lib.R$styleable

any idea why its crashing.

Thanks

**Comment by waqasw** [comment]
I have fixed the problem, I was making  mistake by referencing library.jar after referencing the library instead of the jar everything start working.

**Comment by dextar47** [comment]
what you did to solve this issue?

**Comment by waqasw** [comment]
import the slidingmenu project in eclipse along with your main project, right click on your main project and select properties,on the left side menu list select android at the bottom of the popup in library section click add button and select the slidingmenu project, if you still get errors from the menu select project and clean

**Comment by luvnish19** [comment]
App is crashing with same issue java.lang.NoClassDefFoundError: com.slidingmenu.lib.R$styleable. Only working in latest version (lollipop). Below all versions app is crashing. I had implemented sliding library in Android Studio via import module.

**Comment by mir2018** [comment]
I  i have same problem.. please help me.



--------- beginning of main
*** Service (starter) Create ***
** Service (starter) Start **
** Activity (main) Create, isFirst = true **
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/jeremyfeinstein/slidingmenu/lib/SlidingMenu;
	at anywheresoftware.b4a.objects.SlidingMenuWrapper.Initialize(SlidingMenuWrapper.java:25)
	at b4a.example.main._activity_create(main.java:381)
	at java.lang.reflect.Method.invoke(Native Method)
	at anywheresoftware.b4a.shell.Shell.runMethod(Shell.java:710)
	at anywheresoftware.b4a.shell.Shell.raiseEventImpl(Shell.java:339)
	at anywheresoftware.b4a.shell.Shell.raiseEvent(Shell.java:249)
	at java.lang.reflect.Method.invoke(Native Method)
	at anywheresoftware.b4a.ShellBA.raiseEvent2(ShellBA.java:139)
	at b4a.example.main.afterFirstLayout(main.java:102)
	at b4a.example.main.access$000(main.java:17)
	at b4a.example.main$WaitForLayout.run(main.java:80)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6247)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:872)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.jeremyfeinstein.slidingmenu.lib.SlidingMenu" on path: DexPathList[[zip file "/data/app/b4a.example-1/base.apk"],nativeLibraryDirectories=[/data/app/b4a.example-1/lib/arm64, /system/lib64, /vendor/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 18 more
** Activity (main) Resume **
--------- beginning of system

I Use windows 10 and B4A ..
