### ISSUE TITLE
NoClassDefFoundError: ViewConfigurationCompat

### ISSUE THREAD

**Issue by eliaskaerle** [jfeinstein10/SlidingMenu#448]
After update from git the following error occured

06-07 10:12:13.577: E/AndroidRuntime(11491): java.lang.NoClassDefFoundError: android.support.v4.view.ViewConfigurationCompat
06-07 10:12:13.577: E/AndroidRuntime(11491):    at com.jeremyfeinstein.slidingmenu.lib.CustomViewAbove.initCustomViewAbove(CustomViewAbove.java:167)
06-07 10:12:13.577: E/AndroidRuntime(11491):    at com.jeremyfeinstein.slidingmenu.lib.CustomViewAbove.<init>(CustomViewAbove.java:157)
06-07 10:12:13.577: E/AndroidRuntime(11491):    at com.jeremyfeinstein.slidingmenu.lib.CustomViewAbove.<init>(CustomViewAbove.java:152)
06-07 10:12:13.577: E/AndroidRuntime(11491):    at com.jeremyfeinstein.slidingmenu.lib.SlidingMenu.<init>(SlidingMenu.java:207)
06-07 10:12:13.577: E/AndroidRuntime(11491):    at com.jeremyfeinstein.slidingmenu.lib.SlidingMenu.<init>(SlidingMenu.java:190)
06-07 10:12:13.577: E/AndroidRuntime(11491):    at com.jeremyfeinstein.slidingmenu.lib.SlidingMenu.<init>(SlidingMenu.java:169)
06-07 10:12:13.577: E/AndroidRuntime(11491):    at com.**_.**_.SlideMenu.getMenu(SlideMenu.java:65)
06-07 10:12:13.577: E/AndroidRuntime(11491):    at com.**_.**_.StartScreenActivity.onCreate(StartScreenActivity.java:78)
06-07 10:12:13.577: E/AndroidRuntime(11491):    at android.app.Activity.performCreate(Activity.java:5250)
06-07 10:12:13.577: E/AndroidRuntime(11491):    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1097)
06-07 10:12:13.577: E/AndroidRuntime(11491):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2210)
06-07 10:12:13.577: E/AndroidRuntime(11491):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2296)
06-07 10:12:13.577: E/AndroidRuntime(11491):    at android.app.ActivityThread.access$700(ActivityThread.java:151)
06-07 10:12:13.577: E/AndroidRuntime(11491):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1281)
06-07 10:12:13.577: E/AndroidRuntime(11491):    at android.os.Handler.dispatchMessage(Handler.java:99)
06-07 10:12:13.577: E/AndroidRuntime(11491):    at android.os.Looper.loop(Looper.java:137)
06-07 10:12:13.577: E/AndroidRuntime(11491):    at android.app.ActivityThread.main(ActivityThread.java:5293)
06-07 10:12:13.577: E/AndroidRuntime(11491):    at java.lang.reflect.Method.invokeNative(Native Method)
06-07 10:12:13.577: E/AndroidRuntime(11491):    at java.lang.reflect.Method.invoke(Method.java:511)
06-07 10:12:13.577: E/AndroidRuntime(11491):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
06-07 10:12:13.577: E/AndroidRuntime(11491):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
06-07 10:12:13.577: E/AndroidRuntime(11491):    at dalvik.system.NativeStart.main(Native Method)

**Comment by eliaskaerle** [comment]
my bad: adding the android-support-v4.jar in the lib folder to the build pahth did the trick. see http://stackoverflow.com/questions/9831019/updated-sdk-version-getting-classnotfoundexception-android-support-v4-view-vie?answertab=active#tab-top
