### ISSUE TITLE
inflating exception

### ISSUE THREAD

**Issue by dos1in** [jfeinstein10/SlidingMenu#474]
Thank you for your job! I goto make SlidingFragmentActivity extends SherlockFragmentActivity, then I'm using extends SlidingFragmentActivity, I get this exception when I start the app in the library files.

java.lang.ClassCastException: android.widget.LinearLayout cannot be cast to com.jeremyfeinstein.slidingmenu.lib.SlidingMenu
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2110)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2135)
        at android.app.ActivityThread.access$700(ActivityThread.java:131)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1228)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:137)
        at android.app.ActivityThread.main(ActivityThread.java:4866)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:511)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
        at dalvik.system.NativeStart.main(Native Method)
        Caused by: java.lang.ClassCastException: android.widget.LinearLayout cannot be cast to com.jeremyfeinstein.slidingmenu.lib.SlidingMenu
        at com.jeremyfeinstein.slidingmenu.lib.app.SlidingActivityHelper.onCreate(SlidingActivityHelper.java:45)
        at com.jeremyfeinstein.slidingmenu.lib.app.SlidingFragmentActivity.onCreate(SlidingFragmentActivity.java:22)

**Comment by saynull** [comment]
android.widget.LinearLayout cannot be cast to com.jeremyfeinstein.slidingmenu.lib.SlidingMenu

Your LinearLayout canot be cast to com.jeremyfeinstein.slidingmenu.lib.SlidingMenu.
Should any part of your source code that can find the source of the incorrect.
