### ISSUE TITLE
java.lang.NumberFormatException: Invalid int: "@16974053"

### ISSUE THREAD

**Issue by gflarity** [jfeinstein10/SlidingMenu#500]
Hi,

First, thank you for making this available. It looks really awesome.

I'm trying to follow the simple example using Android Studio instead of eclipse. I believe I've set it up correctly... Perhaps I still need to do something for setup though?

Here's the description:

1) To even get it to compile I had to had a couple resources (dimen, drawable shadow etc). 
2) Now I get an error and the app crashes. The line that causes the crash is below, followed by the stack trace.

Thanks in advance for your time.

int mode = ta.getInt(R.styleable.SlidingMenu_mode, LEFT); //SlidingMenu.java:236

7-27 11:50:32.366  14883-14883/? E/AndroidRuntime: FATAL EXCEPTION: main
        java.lang.RuntimeException: Unable to start activity ComponentInfo{com.avidtap.pos/com.avidtap.pos.MainActivity}: java.lang.NumberFormatException: Invalid int: "@16974053"
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2180)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2230)
        at android.app.ActivityThread.access$600(ActivityThread.java:141)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:137)
        at android.app.ActivityThread.main(ActivityThread.java:5041)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:511)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
        at dalvik.system.NativeStart.main(Native Method)
        Caused by: java.lang.NumberFormatException: Invalid int: "@16974053"
        at java.lang.Integer.invalidInt(Integer.java:138)
        at java.lang.Integer.parse(Integer.java:375)
        at java.lang.Integer.parseInt(Integer.java:366)
        at com.android.internal.util.XmlUtils.convertValueToInt(XmlUtils.java:123)
        at android.content.res.TypedArray.getInt(TypedArray.java:254)
        at com.jeremyfeinstein.slidingmenu.lib.SlidingMenu.<init>(SlidingMenu.java:236)
        at com.jeremyfeinstein.slidingmenu.lib.SlidingMenu.<init>(SlidingMenu.java:192)
        at com.jeremyfeinstein.slidingmenu.lib.SlidingMenu.<init>(SlidingMenu.java:171)
        at com.avidtap.pos.MainActivity.onCreate(MainActivity.java:85)
        at android.app.Activity.performCreate(Activity.java:5104)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1080)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2144)
        ... 11 more

**Comment by gflarity** [comment]
FYIU, I tried using eclipse and I'm seeing the exact same issue.

**Comment by jxljf** [comment]
---

该邮件从移动设备发送

------------------ 原始邮件 ------------------
发件人: "Geoff Flarity"notifications@github.com
发送时间: 2013年7月28日(星期天) 凌晨0:48
收件人: "jfeinstein10/SlidingMenu"SlidingMenu@noreply.github.com;
主题: Re: [SlidingMenu] java.lang.NumberFormatException: Invalid int:"@16974053" (#500)

FYIU, I tried using eclipse and I'm seeing the exact same issue.

&mdash;

**Comment by gflarity** [comment]
So I gave on using Android Studio and got it sort of working in eclipse by importing the sources into a new project and including that project as a dependency.
