### ISSUE TITLE
IndexOutOfBoundsException Crashing

### ISSUE THREAD

**Issue by bdonahue** [jfeinstein10/SlidingMenu#520]
java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:251)
at java.util.ArrayList.get(ArrayList.java:304)
at android.widget.HeaderViewListAdapter.isEnabled(HeaderViewListAdapter.java:164)
at android.widget.ListView.dispatchDraw(ListView.java:3193)
at android.view.View.draw(View.java:13770)
at android.widget.AbsListView.draw(AbsListView.java:4395)
at android.view.View.getDisplayList(View.java:12718)
at android.view.View.getDisplayList(View.java:12762)
at android.view.View.draw(View.java:13491)
at android.view.ViewGroup.drawChild(ViewGroup.java:3219)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3089)
at android.view.View.getDisplayList(View.java:12716)
at android.view.View.getDisplayList(View.java:12762)
at android.view.View.draw(View.java:13491)
at android.view.ViewGroup.drawChild(ViewGroup.java:3219)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3089)
at android.view.View.getDisplayList(View.java:12716)
at android.view.View.getDisplayList(View.java:12762)
at android.view.View.draw(View.java:13491)
at android.view.ViewGroup.drawChild(ViewGroup.java:3219)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3089)
at android.view.View.draw(View.java:13770)
at android.view.View.getDisplayList(View.java:12718)
at android.view.View.getDisplayList(View.java:12762)
at android.view.View.draw(View.java:13491)
at android.view.ViewGroup.drawChild(ViewGroup.java:3219)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3089)
at com.jeremyfeinstein.slidingmenu.lib.CustomViewAbove.dispatchDraw(CustomViewAbove.java:835)
at android.view.View.draw(View.java:13770)
at android.view.View.getDisplayList(View.java:12718)
at android.view.View.getDisplayList(View.java:12762)
at android.view.View.draw(View.java:13491)
at android.view.ViewGroup.drawChild(ViewGroup.java:3219)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3089)
at android.view.View.getDisplayList(View.java:12716)
at android.view.View.getDisplayList(View.java:12762)
at android.view.View.draw(View.java:13491)
at android.view.ViewGroup.drawChild(ViewGroup.java:3219)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3089)
at android.view.View.draw(View.java:13770)
at android.widget.FrameLayout.draw(FrameLayout.java:467)
at android.view.View.getDisplayList(View.java:12718)
at android.view.View.getDisplayList(View.java:12762)
at android.view.View.draw(View.java:13491)
at android.view.ViewGroup.drawChild(ViewGroup.java:3219)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3089)
at android.view.View.getDisplayList(View.java:12716)
at android.view.View.getDisplayList(View.java:12762)
at android.view.View.draw(View.java:13491)
at android.view.ViewGroup.drawChild(ViewGroup.java:3219)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3089)
at android.view.View.draw(View.java:13770)
at android.widget.FrameLayout.draw(FrameLayout.java:467)
at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2396)
at android.view.View.getDisplayList(View.java:12718)
at android.view.View.getDisplayList(View.java:12762)
at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:1144)
at android.view.ViewRootImpl.draw(ViewRootImpl.java:2301)
at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2173)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1981)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1131)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4611)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:725)
at android.view.Choreographer.doCallbacks(Choreographer.java:555)
at android.view.Choreographer.doFrame(Choreographer.java:525)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:711)
at android.os.Handler.handleCallback(Handler.java:615)
at android.os.Handler.dispatchMessage(Handler.java:92)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:4898)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1008)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:775)
at dalvik.system.NativeStart.main(Native Method)

**Comment by bakua** [comment]
Same here... no idea what is causing this. I have activity with sliding menu and content frame layout for fragments. Content fragments has 3 linearLayouts inside (all are w:match_parent h:match_parent) and I hide/show them when I need. But when I show 1 and hide others then above exception is thrown.

**Comment by liganisme** [comment]
same problem in android5.0,have you any idea to resolve it?
