### ISSUE TITLE
Crashbug on startup (only Android 4.3)

### ISSUE THREAD

**Issue by rekire** [jfeinstein10/SlidingMenu#528]
I have a wired problem with this lib. In my most complex activity I'll get an CassCastException, but I don't know why. Here is my stacktrace:

```
java.lang.ClassCastException: android.widget.LinearLayout$LayoutParams cannot be cast to com.android.internal.widget.ActionBarOverlayLayout$LayoutParams
    at com.android.internal.widget.ActionBarOverlayLayout.applyInsets(ActionBarOverlayLayout.java:147)
    at com.android.internal.widget.ActionBarOverlayLayout.onMeasure(ActionBarOverlayLayout.java:292)
    at android.view.View.measure(View.java:15848)
    at com.jeremyfeinstein.slidingmenu.lib.CustomViewAbove.onMeasure(CustomViewAbove.java:445)
    at android.view.View.measure(View.java:15848)
    at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:728)
    at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:477)
    at android.view.View.measure(View.java:15848)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5008)
    at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
    at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2189)
    at android.view.View.measure(View.java:15848)
    at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:1905)
    at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1104)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1284)
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1004)
    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5481)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:749)
    at android.view.Choreographer.doCallbacks(Choreographer.java:562)
    at android.view.Choreographer.doFrame(Choreographer.java:532)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:735)
    at android.os.Handler.handleCallback(Handler.java:730)
    at android.os.Handler.dispatchMessage(Handler.java:92)
    at android.os.Looper.loop(Looper.java:137)
    at android.app.ActivityThread.main(ActivityThread.java:5103)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:525)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
    at dalvik.system.NativeStart.main(Native Method)
```

I tested my code on Android API levels 10, 17 and 18 where only Android 4.3 (18) crashes.

If I should add some code please tell me, but I cannot post everything there are about 10 related classes and at the moment I have no time for a minimal example.

Please note: The line numbers can be a little wrong I added two extra try catches for testing.

**Comment by youxiachai** [comment]
you can test it

```
 <item name="android:windowActionBar">false</item>
```

not use default actionbar

**Comment by rekire** [comment]
I found after long searching this two lines of code:

```
ViewGroup root = (ViewGroup)findViewById(android.R.id.content);
root.setLayoutParams(new LinearLayout.LayoutParams(-1, -1));
```

I cannot remember the reason for that, but after removing it the class cast exception was gone.

**Comment by bananabastard** [comment]
you had to use ViewGroup.LayoutParams instead of LinearLayout ones
