### ISSUE TITLE
ArithmeticException

### ISSUE THREAD

**Issue by Tombarr** [jfeinstein10/SlidingMenu#54]
I just noticed this today and thought that I would report it, it seems that there is an issue with the following line:

```
final int position = xpos / widthWithMargin;
```

Now I know what I did in this case was call `setBehindOffset` with a variable width calculated by screen size, set to a maximum of the window's width. On my Motorola Droid X the resolution is 480x800 and I called `setBehindOffset` with 480 using `SlidingMenu.TOUCHMODE_MARGIN`. 
I've since put the touch mode in a conditional statement, but to spare what might cause issue in the future I would always check for zero before dividing. 

```
java.lang.ArithmeticException: divide by zero
    at com.slidingmenu.lib.CustomViewAbove.pageScrolled(CustomViewAbove.java:929)
    at com.slidingmenu.lib.CustomViewAbove.onTouchEvent(CustomViewAbove.java:1268)
    at android.view.View.dispatchTouchEvent(View.java:3885)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:903)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:942)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:942)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:942)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:942)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:942)
    at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:1919)
    at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1186)
    at android.app.Activity.dispatchTouchEvent(Activity.java:2142)
    at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:1903)
    at android.view.ViewRoot.deliverPointerEvent(ViewRoot.java:2194)
    at android.view.ViewRoot.handleMessage(ViewRoot.java:1878)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:130)
    at android.app.ActivityThread.main(ActivityThread.java:3806)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:507)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
    at dalvik.system.NativeStart.main(Native Method)
```

**Comment by jfeinstein10** [comment]
Probably doesn't apply any more (this is a very old issue)
