### ISSUE TITLE
java.lang.IllegalArgumentException: pointerIndex out of range

### ISSUE THREAD

**Issue by maddestiny** [jfeinstein10/SlidingMenu#593]
I found it in bugsens, so i don't know sequencing for call this bug
os version 4.1.2

i don't know version of your library? i downloaded it at november 22

java.lang.IllegalArgumentException: pointerIndex out of range
at android.view.MotionEvent.nativeGetAxisValue(Native Method)
at android.view.MotionEvent.getX(MotionEvent.java:1981)
at android.support.v4.view.MotionEventCompatEclair.getX(MotionEventCompatEclair.java:32)
at android.support.v4.view.MotionEventCompat$EclairMotionEventVersionImpl.getX(MotionEventCompat.java:91)
at android.support.v4.view.MotionEventCompat.getX(MotionEventCompat.java:219)
at com.jeremyfeinstein.slidingmenu.lib.CustomViewAbove.determineDrag(CustomViewAbove.java:785)
at com.jeremyfeinstein.slidingmenu.lib.CustomViewAbove.onTouchEvent(CustomViewAbove.java:701)
at android.view.View.dispatchTouchEvent(View.java:7255)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2235)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1932)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2241)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1946)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2241)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1946)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2241)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1946)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2241)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1946)
at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:1968)
at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1420)
at android.app.Activity.dispatchTouchEvent(Activity.java:2428)
at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:1916)
at android.view.View.dispatchPointerEvent(View.java:7435)
at android.view.ViewRootImpl.deliverPointerEvent(ViewRootImpl.java:3610)
at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:3538)
at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:4790)
at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:4750)
at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:4902)
at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:179)
at android.os.MessageQueue.nativePollOnce(Native Method)
at android.os.MessageQueue.next(MessageQueue.java:125)
at android.os.Looper.loop(Looper.java:140)
at android.app.ActivityThread.main(ActivityThread.java:5297)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
at dalvik.system.NativeStart.main(Native Method)

**Comment by mjkohoh** [comment]
It has been fixed in recently vision.

**Comment by mjkohoh** [comment]
It has been fixed in recently vision.
