### ISSUE TITLE
java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@408cbfb8

### ISSUE THREAD

**Issue by ntanduc2288** [jfeinstein10/SlidingMenu#654]
Hi Jeremy,

Sometime i got error:
"java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@408cbfb8
       at android.graphics.Canvas.throwIfRecycled(Canvas.java:955)
       at android.graphics.Canvas.drawBitmap(Canvas.java:1044)
       at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:325)
       at android.widget.ImageView.onDraw(ImageView.java:872)
       at android.view.View.draw(View.java:6880)
       at android.view.ViewGroup.drawChild(ViewGroup.java:1646)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
       at android.view.View.draw(View.java:6883)
       at android.view.ViewGroup.drawChild(ViewGroup.java:1646)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
       at android.view.ViewGroup.drawChild(ViewGroup.java:1644)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
       at android.widget.AbsListView.dispatchDraw(AbsListView.java:1480)
       at android.widget.ListView.dispatchDraw(ListView.java:3138)
       at android.view.View.draw(View.java:6986)
       at android.widget.AbsListView.draw(AbsListView.java:2588)
       at android.view.ViewGroup.drawChild(ViewGroup.java:1646)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
       at android.view.View.draw(View.java:6883)
       at android.view.ViewGroup.drawChild(ViewGroup.java:1646)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
       at android.view.ViewGroup.drawChild(ViewGroup.java:1644)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
       at android.view.View.draw(View.java:6883)
       at android.view.ViewGroup.drawChild(ViewGroup.java:1646)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
       at com.jeremyfeinstein.slidingmenu.lib.CustomViewAbove.dispatchDraw(CustomViewAbove.java:827)
       at android.view.View.draw(View.java:6883)
       at android.view.ViewGroup.drawChild(ViewGroup.java:1646)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
       at android.view.ViewGroup.drawChild(ViewGroup.java:1644)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
       at android.view.ViewGroup.drawChild(ViewGroup.java:1644)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
       at android.view.View.draw(View.java:6883)
       at android.widget.FrameLayout.draw(FrameLayout.java:357)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:1874)
       at android.view.ViewRoot.draw(ViewRoot.java:1524)
       at android.view.ViewRoot.performTraversals(ViewRoot.java:1260)
       at android.view.ViewRoot.handleMessage(ViewRoot.java:1861)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:123)
       at android.app.ActivityThread.main(ActivityThread.java:3729)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:507)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:874)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:632)
       at dalvik.system.NativeStart.main(NativeStart.java)"

Please help me to fix it.
Thanks!

**Comment by ChanningSun** [comment]
same here...

**Comment by glm-mawla** [comment]
check image path? if image path is not valid then this error shows.
you need to pass valid image path or image source.
