### ISSUE TITLE
Null Pointer Exception in SlidingFragmentActivity

### ISSUE THREAD

**Issue by ghost** [jfeinstein10/SlidingMenu#664]
I am using an Activity which extends SlidingMenuFragment, But i am getting an crash in the app .This crash occurs someTime only, seen in the case when app navigate from my app to some other app. From the log, it seem that android had killed my activity and trying to recreate the issue occurs. What puzzles me is that 'mHealper' where the crash occurs in SlidingFragmentActivity, cannot be null as in onCreate() you are initializing it. Please help me fix the crash. Please find the crash log below. 

UncaughtException stack trace:

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.xxxxx.xxx/com.xxxxx.xxx.xxx.xxx.MainActivity}: java.lang.NullPointerException
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2184)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233)
at android.app.ActivityThread.access$800(ActivityThread.java:135)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:136)
at android.app.ActivityThread.main(ActivityThread.java:5001)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
at com.xxxxx.xxx.slidingmenu.lib.activities.SlidingFragmentActivity.findViewById(SlidingFragmentActivity.java:42)
at android.app.Activity$1.findViewById(Activity.java:727)
at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:880)
at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1062)
at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1044)
at android.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:1853)
at android.app.Activity.performCreate(Activity.java:5234)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2148)
... 11 more

**Comment by Mansoor17** [comment]
Find your error here,
double click on com.your projectname.xxx in logcat it will take u at the code fragment where Null Pointer Exception is occurring. check your code what's going wrong or show me your code so that i check and find error.
I think this will help you

**Comment by doug-nara** [comment]
This issue seemed similar to the one on http://stackoverflow.com/questions/15100508/forced-close-in-my-application-after-using-a-task-killer/27153514#27153514
