### ISSUE TITLE
Apps Force Close when the Menu is multitouched

### ISSUE THREAD

**Issue by SteveEdson** [jfeinstein10/SlidingMenu#68]
To reproduce, just open the menu and tap with 2 fingers.

I've found that the example app experiences this issue as well. 

Stack trace

```
09-10 16:27:53.005: E/InputEventReceiver(21661): Exception dispatching input event.
09-10 16:27:53.005: E/MessageQueue-JNI(21661): Exception in MessageQueue callback: handleReceiveCallback
09-10 16:27:53.040: E/MessageQueue-JNI(21661): java.lang.IllegalArgumentException: pointerIndex out of range
09-10 16:27:53.040: E/MessageQueue-JNI(21661):  at android.view.MotionEvent.nativeGetAxisValue(Native Method)
09-10 16:27:53.040: E/MessageQueue-JNI(21661):  at android.view.MotionEvent.getX(MotionEvent.java:1981)
09-10 16:27:53.040: E/MessageQueue-JNI(21661):  at android.support.v4.view.MotionEventCompatEclair.getX(MotionEventCompatEclair.java:32)
09-10 16:27:53.040: E/MessageQueue-JNI(21661):  at android.support.v4.view.MotionEventCompat$EclairMotionEventVersionImpl.getX(MotionEventCompat.java:86)
09-10 16:27:53.040: E/MessageQueue-JNI(21661):  at android.support.v4.view.MotionEventCompat.getX(MotionEventCompat.java:210)
09-10 16:27:53.040: E/MessageQueue-JNI(21661):  at com.slidingmenu.lib.CustomViewAbove.onInterceptTouchEvent(CustomViewAbove.java:728)
09-10 16:27:53.040: E/MessageQueue-JNI(21661):  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1822)
09-10 16:27:53.040: E/MessageQueue-JNI(21661):  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2198)
09-10 16:27:53.040: E/MessageQueue-JNI(21661):  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1877)
09-10 16:27:53.040: E/MessageQueue-JNI(21661):  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2176)
09-10 16:27:53.040: E/MessageQueue-JNI(21661):  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1919)
09-10 16:27:53.040: E/MessageQueue-JNI(21661):  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2176)
09-10 16:27:53.040: E/MessageQueue-JNI(21661):  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1919)
09-10 16:27:53.040: E/MessageQueue-JNI(21661):  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2176)
09-10 16:27:53.040: E/MessageQueue-JNI(21661):  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1919)
09-10 16:27:53.040: E/MessageQueue-JNI(21661):  at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:1926)
09-10 16:27:53.040: E/MessageQueue-JNI(21661):  at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1380)
09-10 16:27:53.040: E/MessageQueue-JNI(21661):  at android.app.Activity.dispatchTouchEvent(Activity.java:2396)
09-10 16:27:53.040: E/MessageQueue-JNI(21661):  at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:1874)
09-10 16:27:53.040: E/MessageQueue-JNI(21661):  at android.view.View.dispatchPointerEvent(View.java:7307)
09-10 16:27:53.040: E/MessageQueue-JNI(21661):  at android.view.ViewRootImpl.deliverPointerEvent(ViewRootImpl.java:3172)
09-10 16:27:53.040: E/MessageQueue-JNI(21661):  at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:3117)
09-10 16:27:53.040: E/MessageQueue-JNI(21661):  at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:4153)
09-10 16:27:53.040: E/MessageQueue-JNI(21661):  at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:4132)
09-10 16:27:53.040: E/MessageQueue-JNI(21661):  at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:4224)
09-10 16:27:53.040: E/MessageQueue-JNI(21661):  at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:171)
09-10 16:27:53.040: E/MessageQueue-JNI(21661):  at android.os.MessageQueue.nativePollOnce(Native Method)
09-10 16:27:53.040: E/MessageQueue-JNI(21661):  at android.os.MessageQueue.next(MessageQueue.java:125)
09-10 16:27:53.040: E/MessageQueue-JNI(21661):  at android.os.Looper.loop(Looper.java:124)
09-10 16:27:53.040: E/MessageQueue-JNI(21661):  at android.app.ActivityThread.main(ActivityThread.java:4939)
09-10 16:27:53.040: E/MessageQueue-JNI(21661):  at java.lang.reflect.Method.invokeNative(Native Method)
09-10 16:27:53.040: E/MessageQueue-JNI(21661):  at java.lang.reflect.Method.invoke(Method.java:511)
09-10 16:27:53.040: E/MessageQueue-JNI(21661):  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:791)
09-10 16:27:53.040: E/MessageQueue-JNI(21661):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:558)
09-10 16:27:53.040: E/MessageQueue-JNI(21661):  at dalvik.system.NativeStart.main(Native Method)
09-10 16:27:53.045: D/AndroidRuntime(21661): Shutting down VM
09-10 16:27:53.050: W/dalvikvm(21661): threadid=1: thread exiting with uncaught exception (group=0x40ccc300)
```

**Comment by Tombarr** [comment]
I actually get this exact same error ever time I click with two or more fingers. Here is my stack trace:

```
09-10 12:38:00.670: E/InputEventReceiver(15005): Exception dispatching input event.
09-10 12:38:00.670: E/MessageQueue-JNI(15005): Exception in MessageQueue callback: handleReceiveCallback
09-10 12:38:00.732: E/MessageQueue-JNI(15005): java.lang.IllegalArgumentException: pointerIndex out of range
09-10 12:38:00.732: E/MessageQueue-JNI(15005):  at android.view.MotionEvent.nativeGetAxisValue(Native Method)
09-10 12:38:00.732: E/MessageQueue-JNI(15005):  at android.view.MotionEvent.getX(MotionEvent.java:1981)
09-10 12:38:00.732: E/MessageQueue-JNI(15005):  at android.support.v4.view.MotionEventCompatEclair.getX(MotionEventCompatEclair.java:32)
09-10 12:38:00.732: E/MessageQueue-JNI(15005):  at android.support.v4.view.MotionEventCompat$EclairMotionEventVersionImpl.getX(MotionEventCompat.java:86)
09-10 12:38:00.732: E/MessageQueue-JNI(15005):  at android.support.v4.view.MotionEventCompat.getX(MotionEventCompat.java:210)
09-10 12:38:00.732: E/MessageQueue-JNI(15005):  at com.slidingmenu.lib.CustomViewAbove.onInterceptTouchEvent(CustomViewAbove.java:729)
09-10 12:38:00.732: E/MessageQueue-JNI(15005):  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1822)
09-10 12:38:00.732: E/MessageQueue-JNI(15005):  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2198)
09-10 12:38:00.732: E/MessageQueue-JNI(15005):  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1877)
09-10 12:38:00.732: E/MessageQueue-JNI(15005):  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2176)
09-10 12:38:00.732: E/MessageQueue-JNI(15005):  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1919)
09-10 12:38:00.732: E/MessageQueue-JNI(15005):  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2176)
09-10 12:38:00.732: E/MessageQueue-JNI(15005):  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1919)
09-10 12:38:00.732: E/MessageQueue-JNI(15005):  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2176)
09-10 12:38:00.732: E/MessageQueue-JNI(15005):  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1919)
09-10 12:38:00.732: E/MessageQueue-JNI(15005):  at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:1926)
09-10 12:38:00.732: E/MessageQueue-JNI(15005):  at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1380)
09-10 12:38:00.732: E/MessageQueue-JNI(15005):  at android.app.Activity.dispatchTouchEvent(Activity.java:2396)
09-10 12:38:00.732: E/MessageQueue-JNI(15005):  at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:1874)
09-10 12:38:00.732: E/MessageQueue-JNI(15005):  at android.view.View.dispatchPointerEvent(View.java:7307)
09-10 12:38:00.732: E/MessageQueue-JNI(15005):  at android.view.ViewRootImpl.deliverPointerEvent(ViewRootImpl.java:3172)
09-10 12:38:00.732: E/MessageQueue-JNI(15005):  at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:3117)
09-10 12:38:00.732: E/MessageQueue-JNI(15005):  at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:4153)
09-10 12:38:00.732: E/MessageQueue-JNI(15005):  at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:4132)
09-10 12:38:00.732: E/MessageQueue-JNI(15005):  at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:4224)
09-10 12:38:00.732: E/MessageQueue-JNI(15005):  at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:171)
09-10 12:38:00.732: E/MessageQueue-JNI(15005):  at android.os.MessageQueue.nativePollOnce(Native Method)
09-10 12:38:00.732: E/MessageQueue-JNI(15005):  at android.os.MessageQueue.next(MessageQueue.java:125)
09-10 12:38:00.732: E/MessageQueue-JNI(15005):  at android.os.Looper.loop(Looper.java:124)
09-10 12:38:00.732: E/MessageQueue-JNI(15005):  at android.app.ActivityThread.main(ActivityThread.java:4939)
09-10 12:38:00.732: E/MessageQueue-JNI(15005):  at java.lang.reflect.Method.invokeNative(Native Method)
09-10 12:38:00.732: E/MessageQueue-JNI(15005):  at java.lang.reflect.Method.invoke(Method.java:511)
09-10 12:38:00.732: E/MessageQueue-JNI(15005):  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:791)
09-10 12:38:00.732: E/MessageQueue-JNI(15005):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:558)
09-10 12:38:00.732: E/MessageQueue-JNI(15005):  at dalvik.system.NativeStart.main(Native Method)
09-10 12:38:00.732: D/AndroidRuntime(15005): Shutting down VM
09-10 12:38:00.732: W/dalvikvm(15005): threadid=1: thread exiting with uncaught exception (group=0x41992300)
09-10 12:38:00.748: E/AndroidRuntime(15005): FATAL EXCEPTION: main
09-10 12:38:00.748: E/AndroidRuntime(15005): java.lang.IllegalArgumentException: pointerIndex out of range
09-10 12:38:00.748: E/AndroidRuntime(15005):    at android.view.MotionEvent.nativeGetAxisValue(Native Method)
09-10 12:38:00.748: E/AndroidRuntime(15005):    at android.view.MotionEvent.getX(MotionEvent.java:1981)
09-10 12:38:00.748: E/AndroidRuntime(15005):    at android.support.v4.view.MotionEventCompatEclair.getX(MotionEventCompatEclair.java:32)
09-10 12:38:00.748: E/AndroidRuntime(15005):    at android.support.v4.view.MotionEventCompat$EclairMotionEventVersionImpl.getX(MotionEventCompat.java:86)
09-10 12:38:00.748: E/AndroidRuntime(15005):    at android.support.v4.view.MotionEventCompat.getX(MotionEventCompat.java:210)
09-10 12:38:00.748: E/AndroidRuntime(15005):    at com.slidingmenu.lib.CustomViewAbove.onInterceptTouchEvent(CustomViewAbove.java:728)
09-10 12:38:00.748: E/AndroidRuntime(15005):    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1822)
09-10 12:38:00.748: E/AndroidRuntime(15005):    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2198)
09-10 12:38:00.748: E/AndroidRuntime(15005):    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1877)
09-10 12:38:00.748: E/AndroidRuntime(15005):    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2176)
09-10 12:38:00.748: E/AndroidRuntime(15005):    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1919)
09-10 12:38:00.748: E/AndroidRuntime(15005):    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2176)
09-10 12:38:00.748: E/AndroidRuntime(15005):    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1919)
09-10 12:38:00.748: E/AndroidRuntime(15005):    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2176)
09-10 12:38:00.748: E/AndroidRuntime(15005):    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1919)
09-10 12:38:00.748: E/AndroidRuntime(15005):    at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:1926)
09-10 12:38:00.748: E/AndroidRuntime(15005):    at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1380)
09-10 12:38:00.748: E/AndroidRuntime(15005):    at android.app.Activity.dispatchTouchEvent(Activity.java:2396)
09-10 12:38:00.748: E/AndroidRuntime(15005):    at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:1874)
09-10 12:38:00.748: E/AndroidRuntime(15005):    at android.view.View.dispatchPointerEvent(View.java:7307)
09-10 12:38:00.748: E/AndroidRuntime(15005):    at android.view.ViewRootImpl.deliverPointerEvent(ViewRootImpl.java:3172)
09-10 12:38:00.748: E/AndroidRuntime(15005):    at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:3117)
09-10 12:38:00.748: E/AndroidRuntime(15005):    at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:4153)
09-10 12:38:00.748: E/AndroidRuntime(15005):    at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:4132)
09-10 12:38:00.748: E/AndroidRuntime(15005):    at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:4224)
09-10 12:38:00.748: E/AndroidRuntime(15005):    at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:171)
09-10 12:38:00.748: E/AndroidRuntime(15005):    at android.os.MessageQueue.nativePollOnce(Native Method)
09-10 12:38:00.748: E/AndroidRuntime(15005):    at android.os.MessageQueue.next(MessageQueue.java:125)
09-10 12:38:00.748: E/AndroidRuntime(15005):    at android.os.Looper.loop(Looper.java:124)
09-10 12:38:00.748: E/AndroidRuntime(15005):    at android.app.ActivityThread.main(ActivityThread.java:4939)
09-10 12:38:00.748: E/AndroidRuntime(15005):    at java.lang.reflect.Method.invokeNative(Native Method)
09-10 12:38:00.748: E/AndroidRuntime(15005):    at java.lang.reflect.Method.invoke(Method.java:511)
09-10 12:38:00.748: E/AndroidRuntime(15005):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:791)
09-10 12:38:00.748: E/AndroidRuntime(15005):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:558)
09-10 12:38:00.748: E/AndroidRuntime(15005):    at dalvik.system.NativeStart.main(Native Method)
09-10 12:38:00.771: W/ActivityManager(320):   Force finishing activity com.example/.activities.UserActivity
```

**Comment by jfeinstein10** [comment]
Yup, thanks for bringing my attention to this. I'll fix it later tonight after I'm through with my problem sets due tomorrow :/

**Comment by jfeinstein10** [comment]
Alright, I believe this is fixed now. Closing the issue. Let me know what you guys find.
