### ISSUE TITLE
java.lang.stackoverflow exception 

### ISSUE THREAD

**Issue by amcamc** [jfeinstein10/SlidingMenu#701]
I got that error multiple times 

01-24 22:32:14.128: E/AndroidRuntime(4629):     at com.jeremyfeinstein.slidingmenu.lib.CustomViewAbove.dispatchDraw(CustomViewAbove.java:827)

01-24 22:32:14.128: E/AndroidRuntime(4629): java.lang.StackOverflowError
01-24 22:32:14.128: E/AndroidRuntime(4629):     at android.text.Layout.getLineVisibleEnd(Layout.java:1138)
01-24 22:32:14.128: E/AndroidRuntime(4629):     at android.text.Layout.getLineExtent(Layout.java:984)
01-24 22:32:14.128: E/AndroidRuntime(4629):     at android.text.Layout.drawText(Layout.java:345)
01-24 22:32:14.128: E/AndroidRuntime(4629):     at android.text.Layout.draw(Layout.java:221)
01-24 22:32:14.128: E/AndroidRuntime(4629):     at android.widget.TextView.onDraw(TextView.java:5218)
01-24 22:32:14.128: E/AndroidRuntime(4629):     at android.view.View.draw(View.java:13806)
01-24 22:32:14.128: E/AndroidRuntime(4629):     at android.view.View.getDisplayList(View.java:12757)
01-24 22:32:14.128: E/AndroidRuntime(4629):     at android.view.View.getDisplayList(View.java:12801)
01-24 22:32:14.128: E/AndroidRuntime(4629):     at android.view.View.draw(View.java:13530)
01-24 22:32:14.128: E/AndroidRuntime(4629):     at android.view.ViewGroup.drawChild(ViewGroup.java:3228)
01-24 22:32:14.128: E/AndroidRuntime(4629):     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3093)
01-24 22:32:14.128: E/AndroidRuntime(4629):     at android.view.View.draw(View.java:13809)
01-24 22:32:14.128: E/AndroidRuntime(4629):     at android.widget.FrameLayout.draw(FrameLayout.java:467)
01-24 22:32:14.128: E/AndroidRuntime(4629):     at android.view.View.getDisplayList(View.java:12757)

**Comment by uma-dnp** [comment]
I also got the same

**Comment by jaswinderwadali** [comment]
Did anyone solve this issue?
