### ISSUE TITLE
Issue with onMeasure() occurring sometimes and crashing app

### ISSUE THREAD

**Issue by Cartman34** [jfeinstein10/SlidingMenu#731]
hi,

I'm using your great library and i got a report about an error.
I don't have much information about this error, but i could share you the report because your lib may be the source of the issue.

The lib may be or may be not in fault. But i found this error could occur when overridden onMeasure() is not calling the super onMeasure() and the onMeasure() method of com.jeremyfeinstein.slidingmenu.lib.CustomViewAbove is not calling super.onMeasure().

> java.lang.IllegalStateException: onMeasure() did not set the measured dimension by calling setMeasuredDimension()
>   at android.view.View.measure(View.java:16657)
>   at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:719)
>   at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:455)
>   at android.view.View.measure(View.java:16645)
>   at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:719)
>   at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:455)
>   at android.view.View.measure(View.java:16645)
>   at android.widget.ScrollView.measureChildWithMargins(ScrollView.java:1226)
>   at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
>   at android.widget.ScrollView.onMeasure(ScrollView.java:326)
>   at android.view.View.measure(View.java:16645)
>   at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
>   at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
>   at android.view.View.measure(View.java:16645)
>   at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
>   at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
>   at android.support.v7.internal.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:124)
>   at android.view.View.measure(View.java:16645)
>   at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
>   at android.support.v7.internal.widget.ActionBarOverlayLayout.onMeasure(ActionBarOverlayLayout.java:444)
>   at android.view.View.measure(View.java:16645)
>   at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
>   at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
>   at android.view.View.measure(View.java:16645)
>   at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
>   at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
>   at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
>   at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
>   at android.view.View.measure(View.java:16645)
>   at com.jeremyfeinstein.slidingmenu.lib.CustomViewAbove.onMeasure(CustomViewAbove.java:456)
>   at android.view.View.measure(View.java:16645)
>   at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:719)
>   at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:455)
>   at android.view.View.measure(View.java:16645)
>   at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
>   at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
>   at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2298)
>   at android.view.View.measure(View.java:16645)
>   at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:1916)
>   at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1113)
>   at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1295)
>   at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1000)
>   at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5622)
>   at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
>   at android.view.Choreographer.doCallbacks(Choreographer.java:574)
>   at android.view.Choreographer.doFrame(Choreographer.java:544)
>   at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
>   at android.os.Handler.handleCallback(Handler.java:733)
>   at android.os.Handler.dispatchMessage(Handler.java:95)
>   at android.os.Looper.loop(Looper.java:212)
>   at android.app.ActivityThread.main(ActivityThread.java:5135)
>   at java.lang.reflect.Method.invokeNative(Native Method)
>   at java.lang.reflect.Method.invoke(Method.java:515)
>   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:878)
>   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
>   at dalvik.system.NativeStart.main(Native Method)

**Comment by HosseinKurd** [comment]
I have this problem Too, when show google map on view .
